# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: WebdriverIO Test FW

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: SetUp NodeJs
      uses: actions/setup-node@v1
      with:
        node-version: 16.3.0

    - uses: actions/checkout@v2
    - name: Run docker-compose 
      run: docker-compose up --exit-code-from wdio-framework
  
    - name: upload artifacts
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: htmlreports
        path: app/allure-results